version: "3.3"
services:

  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5000:5000"

  flask_app_2:
    container_name: flask_app_2
    build:
      context: .
      dockerfile: app_2/Dockerfile
    ports:
      - "5001:5001"
