version: "3.3"
services:

  flask-app:
    container_name: flask-app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5000:5000"

  flask-app-2:
    container_name: flask-app-2
    build:
      context: .
      dockerfile: app_2/Dockerfile
    ports:
      - "5001:5001"
