name: Flask App CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["flask-app","flask-app-2" ]

    steps:
    - uses: actions/checkout@v2
    - name: Build Services
      run: docker-compose up -d --build ${{ matrix.service }}
    - uses: actions/setup-python@v2
    - name: Prepare Test Environment
      run: |
        pip install pytest
        pip install requests
    - name: Test Flask App
      run: pytest ./tests
