name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -f ./app/Dockerfile -t flask-app .
    - name: Run the Docker image
      run: docker run --name flask-app -d -p 5000:5000 flask-app
    - uses: actions/setup-python@v2
    - name: Prepare Test Environment
      run: pip install pytest
    - name: Test Flask App
      run: pytest ./tests
